# Generated by Django 6.0 on 2026-01-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_restaurant_picture_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.URLField(default='https://maps.app.goo.gl/s635cY4K5dwBSeog7', max_length=300),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
